# i3 specific modules

[module/i3_exit]
# custom/text does not intercept fallback for double-click
#type = custom/text

#label = "  EXIT  "
#format = <label>

type = custom/script

exec =  echo "  EXIT  "
format-background = ${colors.alert}

click-left = "$_i3_SCRIPTDIR/i3_event_exit.sh left"
click-right = "$_i3_SCRIPTDIR/i3_event_exit.sh right"
click-middle = "$_i3_SCRIPTDIR/i3_event_exit.sh middle"

#intercept fallback in bar main_i3
double-click-left = " "
double-click-right = " "

scroll-up = "$_i3_SCRIPTDIR/i3_event_exit.sh up"
scroll-down = "$_i3_SCRIPTDIR/i3_event_exit.sh down"

[module/i3_move_left]
type = custom/script

exec = echo "  "
format-foreground = ${colors.secondary}

# Single window movements
click-left = i3-msg move left
click-right = i3-msg move window to output prev
# Workspace movements
double-click-left = i3-msg move window to workspace prev, workspace prev
double-click-right = i3-msg move workspace to output prev

# param 1 = CONTROL, param 2 = BUTTON
scroll-up = "$_i3_SCRIPTDIR/i3_event_move.sh move_left up"
scroll-down = "$_i3_SCRIPTDIR/i3_event_move.sh move_left down"

[module/i3_move_right]
type = custom/script

exec = echo "  "
format-foreground = ${colors.secondary}

# Single window movements
click-left = i3-msg move right
click-right = i3-msg move window to output next
# Workspace movements
double-click-left = i3-msg move window to workspace next, workspace next
double-click-right = i3-msg move workspace to output next

# param 1 = CONTROL, param 2 = BUTTON
scroll-up = "$_i3_SCRIPTDIR/i3_event_move.sh move_right up"
scroll-down = "$_i3_SCRIPTDIR/i3_event_move.sh move_right down"

[module/i3_move_up]
type = custom/script

exec = echo "  "
format-foreground = ${colors.secondary}

click-left = i3-msg move up
double-click-left = i3-msg move window to workspace prev, workspace prev
#intercept fallback in bar main_i3
click-right = " "
double-click-right = " "

# param 1 = CONTROL, param 2 = BUTTON
scroll-up = "$_i3_SCRIPTDIR/i3_event_move.sh move_up up"
scroll-down = "$_i3_SCRIPTDIR/i3_event_move.sh move_up down"

[module/i3_move_down]
type = custom/script

exec = echo "  " 
format-foreground = ${colors.secondary}

click-left = i3-msg move down
double-click-left = i3-msg move window to workspace next, workspace next
#intercept fallback in bar main_i3
click-right = " "
double-click-right = " "

# param 1 = CONTROL, param 2 = BUTTON
scroll-up = "$_i3_SCRIPTDIR/i3_event_move.sh move_down up"
scroll-down = "$_i3_SCRIPTDIR/i3_event_move.sh move_down down"

[module/i3_move_to]
type = custom/script

exec = echo " 󰆾 "
format-foreground = ${colors.secondary}

click-left = "$_i3_SCRIPTDIR/i3_move_to.sh window"
double-click-left = "$_i3_SCRIPTDIR/i3_move_to.sh container"

#intercept fallback in bar main_i3
click-right = " "
double-click-right = " "

# param 1 = CONTROL, param 2 = BUTTON
scroll-up = "$_i3_SCRIPTDIR/i3_event_move.sh move_to up"
scroll-down = "$_i3_SCRIPTDIR/i3_event_move.sh move_to down"

# changed
[module/i3_windows]
type = internal/xwindow
label = %class%: %title%

# left-click info, right-click intercept, scroll up/down
format = %{A1:$_i3_SCRIPTDIR/i3_info_window.sh left:}%{A6:$_i3_SCRIPTDIR/i3_info_window.sh dbl_left:}%{A3:$_i3_SCRIPTDIR/i3_info_window.sh right:}%{A8: :}%{A4:$_i3_SCRIPTDIR/i3_info_window.sh up:}%{A5:$_i3_SCRIPTDIR/i3_info_window.sh down:} <label> %{A}%{A}%{A}%{A}%{A}%{A}

label-minlen = ${app-data.i3_windows_width}
label-maxlen = ${app-data.i3_windows_width}
label-alignment = center

format-prefix = %{A1:$_i3_SCRIPTDIR/i3_event_window.sh left:}%{A6:$_i3_SCRIPTDIR/i3_event_window.sh dbl_left:}%{A2:$_i3_SCRIPTDIR/i3_event_window.sh middle:}%{A3:$_i3_SCRIPTDIR/i3_event_window.sh right:}%{A8:$_i3_SCRIPTDIR/i3_event_window.sh dbl_right:}%{A4:$_i3_SCRIPTDIR/i3_event_window.sh up:}%{A5:$_i3_SCRIPTDIR/i3_event_window.sh down:}  %{A}%{A}%{A}%{A}%{A}%{A}%{A}
format-prefix-foreground = ${colors.secondary}

[module/i3_win]
type = internal/xwindow

label = %title%
label-minlen = ${app-data.i3_win_width}
label-maxlen = ${app-data.i3_win_width}
label-ellipsis = false
label-alignment = center

format = %{A1:$_i3_SCRIPTDIR/i3_info_window.sh left:}%{A3: :}%{A6:$_i3_SCRIPTDIR/i3_info_window.sh dbl_left:}%{A3:$_i3_SCRIPTDIR/i3_info_window.sh right:}%{A8: :}%{A4:$_i3_SCRIPTDIR/i3_info_window.sh up:}%{A5:$_i3_SCRIPTDIR/i3_info_window.sh down:} <label> %{A}%{A}%{A}%{A}%{A}%{A}%{A}

format-prefix = %{A1:$_i3_SCRIPTDIR/i3_event_window.sh left:}%{A6:$_i3_SCRIPTDIR/i3_event_window.sh dbl_left:}%{A2:$_i3_SCRIPTDIR/i3_event_window.sh middle:}%{A3:$_i3_SCRIPTDIR/i3_event_window.sh right:}%{A8:$_i3_SCRIPTDIR/i3_event_window.sh dbl_right:}%{A4:$_i3_SCRIPTDIR/i3_event_window.sh up:}%{A5:$_i3_SCRIPTDIR/i3_event_window.sh down:}  %{A}%{A}%{A}%{A}%{A}%{A}%{A}
format-prefix-foreground = ${colors.secondary}

# changed
[module/i3_workspaces]
type = internal/i3

enable-click = true

show-all = true
strip-wsnumbers = true

# Separator between workspaces
label-separator = " "
label-separator-padding = 1
label-separator-foreground = ${colors.disabled}

format = %{A1:$_i3_SCRIPTDIR/i3_info_workspace.sh left:}%{A3:$_i3_SCRIPTDIR/i3_info_workspace.sh right: }%{A6:$_i3_SCRIPTDIR/i3_info_workspace.sh dbl_left:}<label-state> %{A}%{A}%{A}

label-focused = %name%
label-focused-background = ${colors.background-alt}
label-focused-underline= ${colors.secondary}
label-focused-padding = 1
label-focused-minlen = ${app-data.i3_workspaces_width}
label-focused-maxlen = ${app-data.i3_workspaces_width}
label-focused-ellipsis = false
label-focused-alignment = center

label-visible = %name%
label-visible-padding = 1
label-visible-minlen = ${app-data.i3_workspaces_width}
label-visible-maxlen = ${app-data.i3_workspaces_width}
label-visible-ellipsis = false
label-visible-alignment = center

label-unfocused = %name%
label-unfocused-background = ${colors.background-alt}
label-unfocused-padding = 1
label-unfocused-minlen = ${app-data.i3_workspaces_width}
label-unfocused-maxlen = ${app-data.i3_workspaces_width}
label-unfocused-ellipsis = false
label-unfocused-alignment = center

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1
label-urgent-minlen = ${app-data.i3_workspaces_width}
label-urgent-maxlen = ${app-data.i3_workspaces_width}
label-urgent-ellipsis = false
label-urgent-alignment = center

format-prefix = %{A1:$_i3_SCRIPTDIR/i3_event_workspace.sh left:}%{A6:$_i3_SCRIPTDIR/i3_event_workspace.sh dbl_left:}%{A2:$_i3_SCRIPTDIR/i3_event_workspace.sh middle:}%{A3:$_i3_SCRIPTDIR/i3_event_workspace.sh right:}%{A8:$_i3_SCRIPTDIR/i3_event_workspace.sh dbl_right:}%{A4:$_i3_SCRIPTDIR/i3_event_workspace.sh up:}%{A5:$_i3_SCRIPTDIR/i3_event_workspace.sh down:} 󰷔 %{A}%{A}%{A}%{A}%{A}%{A}%{A}
format-prefix-foreground = ${colors.secondary}
;format-prefix-padding = 1

[module/i3_ws]
type = internal/i3

# Show only focused workspace
pin-workspaces = true
show-urgent = true
enable-click = false
strip-wsnumbers = true

format = %{A1:$_i3_SCRIPTDIR/i3_info_workspace.sh left:}%{A3:$_i3_SCRIPTDIR/i3_info_workspace.sh right: }%{A6:$_i3_SCRIPTDIR/i3_info_workspace.sh dbl_left:}<label-state> %{A}%{A}%{A}

# Only the focused label has content
label-focused = %name%
label-focused-background = ${colors.background-alt}
label-focused-underline= ${colors.secondary}
label-focused-padding = 1
label-focused-minlen = ${app-data.i3_workspaces_width}
label-focused-maxlen = ${app-data.i3_workspaces_width}
label-focused-ellipsis = false
label-focused-alignment = center

# All other states remain completely empty (no memory usage).
label-unfocused =
label-visible =
label-urgent = %name%
label-urgent-background = #bd2c40
label-urgent-padding = 2

format-prefix = %{A1:$_i3_SCRIPTDIR/i3_event_workspace.sh left:}%{A6:$_i3_SCRIPTDIR/i3_event_workspace.sh dbl_left:}%{A2:$_i3_SCRIPTDIR/i3_event_workspace.sh middle:}%{A3:$_i3_SCRIPTDIR/i3_event_workspace.sh right:}%{A8:$_i3_SCRIPTDIR/i3_event_workspace.sh dbl_right:}%{A4:$_i3_SCRIPTDIR/i3_event_workspace.sh up:}%{A5:$_i3_SCRIPTDIR/i3_event_workspace.sh down:} 󰷔 %{A}%{A}%{A}%{A}%{A}%{A}%{A}
format-prefix-foreground = ${colors.secondary}

[module/i3_scratch]
type = custom/script

# Recursive search (..) for the scratchpad workspace and count its floating windows.
exec = "$_i3_SCRIPTDIR/i3_scratch_counter.sh"

tail = true

label = " %output% "
format = <label>
format-background = ${colors.background}

format-prefix = %{A1:$_i3_SCRIPTDIR/i3_event_scratch.sh left:}%{A6:$_i3_SCRIPTDIR/i3_event_scratch.sh dbl_left:}%{A2:$_i3_SCRIPTDIR/i3_event_scratch.sh middle:}%{A3:$_i3_SCRIPTDIR/i3_event_scratch.sh right:}%{A8:$_i3_SCRIPTDIR/i3_event_scratch.sh dbl_right:}%{A4:$_i3_SCRIPTDIR/i3_event_scratch.sh up:}%{A5:$_i3_SCRIPTDIR/i3_event_scratch.sh down:}󰮉%{A}%{A}%{A}%{A}%{A}%{A}%{A}
format-prefix-foreground = ${colors.secondary}

click-left = $_i3_SCRIPTDIR/i3_info_scratch.sh left
click-right = $_i3_SCRIPTDIR/i3_info_scratch.sh right
#intercept fallback in bar main_i3
double-click-left = " "
double-click-right = " "

scroll-up = " "
scroll-down = " "
