# yad icons

i_ok="emc-gtk-ok"
i_apply="emc-gtk-apply"
i_cancel="emc-gtk-cancel"

i_save="emc-document-save"
i_edit="emc-gtk-edit"
i_undo="emc-edit-undo"
i_redo="emc-edit-redo"
i_info="emc-info"
i_error="emc-dialog-error"
i_msg="emc-dialog-information"
i_exit="emc-application-exit"
i_search="emc-search"
i_question="emc-dialog-question"
i_password="emc-dialog-password"

i_software="emc-software-installer"
i_install="emc-software-install"
i_remove="emc-remove"
i_install_pkg="emc-package-install"
i_remove_pkg="emc-package-purge"
i_update="emc-system-software-update"
i_refresh="emc-view-refresh"
i_sysrun="emc-system-run"
i_sys="emc-system-symbolic"
i_trash="emc-user-trash"

i_shutdown="emc-shutdown"
i_reboot="emc-reboot"
i_logout="emc-log-out"

# yad exit codes

readonly yad_save=100
readonly yad_full_install=100
readonly yad_core_install=110
readonly yad_core_sim=110
readonly yad_compare_log=120
readonly yad_ok=0
readonly yad_remove=0
readonly yad_upgrade=0
readonly yad_cancel=1

# yad buttons

BTN_OK() {

	local label=${1:-" OK"}
	local btn_ok=" $label!$i_ok:0"

	printf "%s" "$btn_ok"
}

BTN_APPLY() {

	local label=${1:-" APPLY"}
	local btn_apply=" $label!$i_apply:0"

	printf "%s" "$btn_apply"
}

BTN_CANCEL() {

	local label=${1:-" CANCEL"}
	local btn_cancel=" $label!$i_cancel:1"

	printf "%s" "$btn_cancel"
}

BTN_SAVE() {

	local label=${1:-" SAVE"}
	local btn_save=" $label!$i_save:$yad_save"

	printf "%s" "$btn_save"
}

BTN_INSTALL_PKG() {

	local mode=${1:-"FULL"} exitcode=${2:-$yad_full_install}
	local label=" $mode  INSTALL"

	[ "$mode" = " " ] && label=" INSTALL"

	local btn_install_pkg=" $label!$i_install_pkg:$exitcode"

	printf "%s" "$btn_install_pkg"
}

BTN_REMOVE_PKG() {

	local label=${1:-" REMOVE"} exitcode=${2:-$yad_remove}
	local btn_remove_pkg=" $label!$i_remove_pkg:$exitcode"

	printf "%s" "$btn_remove_pkg"
}
