#applications.ini: configure main and launchbars. Define your apps to start
#STANDALONE EMC Version

# Mainbar Module Configuration
[app-main]

# load your modules
# comment / uncommennt for use

# full module list for i3 1600 x 900 and more
main_modules_right = screenshot display pulseaudio keyboard cpu memory filesys eth wlan date i3_exit

# reduced module list
#main_modules_right = display keyboard date i3_exit

# Module Click Actions
# Define commands for left, right, and double clicks
# Leave blank if you won't start any app with this click

# module cpu
cpu_left = xfce4-taskmanager &
cpu_right =
cpu_dbl_left = cpu-x &
cpu_dbl_right =

#module date
# gnome-calendar takes up a lot of disk space and,
# depending on the system, may start or install unwanted services
date_left = xdg-open https://calendar.google.com/calendar &
date_right =
date_dbl_left = orage &
date_dbl_right =

# module display 
#display_left = reserved for script set_resolution.sh"
display_right =
display_dbl_left = xdg-open $_USERDIR/monitor.ini &
display_dbl_right = xdg-open $_i3_BASEDIR/usr/config_workspaces &

# module eth
#eth_left = reserved for connect/disconnect
eth_right = nm-connection-editor &
eth_dbl_left = $_SCRIPTDIR/chk_download_speed.sh &
eth_dbl_right = lxterminal -e nmtui &

# module filesys
filesys_left = gnome-disks --block-device=/dev/sda &
filesys_right = gparted &
filesys_dbl_left = baobab &
filesys_dbl_right =

# module keyboard
#keyboard_left  reserved for toggle kbd layout
#keyboard_dbl_left reserved for reset kbd layout
keyboard_right = $_SCRIPTDIR/test_keyboard.sh &
keyboard_dbl_right =

# module memory
memory_left = xfce4-taskmanager &
memory_right =
memory_dbl_left = $_SCRIPTDIR/hwinfo.sh &
memory_dbl_right =

# module pulseaudio
#pulseaudio_left = reserved for audio on/off
#pulseaudio_right = reserved for micro on/off
pulseaudio_dbl_left = blueman-manager &
pulseaudio_dbl_right = pavucontrol &

# module screenshot
#screenshot_left reserved for screenshot
#screenshot_dbl_left reserved for partial screenshot
screenshot_right =
screenshot_dbl_right =

# module wlan
#wlan_left = reserved for connect/disconnect
wlan_right = nm-connection-editor &
wlan_dbl_left = $_SCRIPTDIR/chk_download_speed.sh &
wlan_dbl_right = lxterminal -e nmtui &

# Section to access some EMC data
[app-data]

# get value with echo $LANG in terminal
locale = de_DE.UTF-8

# mount point for filesys module
#filesys_mount = /media/user_name/your_device
#filesys_mount = /home
filesys_mount = /

# minimum = 3! Don't change, this is good
i3_workspaces_width = 3
# yes for show
show_mainbar_info_on_start = yes
# width for window module
i3_windows_width = 15
i3_win_width = 3

;dbl_click_time = 350

# Launchbar and Starter Configuration
[app-launch]

# configure your launchbars with starters
launchbar_left_modules_left = audio02 audio01 video01 video02 pic01
launchbar_left_modules_right = dosbox01

launchbar_center_modules_right = fm01 fm02 package02 user_space01 web01 mail01 download01 messenger01 user_space01 terminal01 editor01 search01 user_space01

launchbar_right_modules_left = hw01 printer01 bluetooth01 net01
launchbar_right_modules_right = calendar01 calculator01 office01 pdftool01 scan01

# space
#starter: user_space01 user_space02 user_space03
user_space01_padding = 1
user_space02_padding = 25
user_space03_padding = 50

# use $_SCRIPTDIR to access sripts in $HOME/.config/polybar/i3/script
# use $_USERSCRIPT to acces your scripts in $HOME/.config/polybar/i3/usr/script
# use $_USERDIR to acces $HOME/.config/polybar/i3/usr

# categories like xfce4 appfinder but no duplicate keys
# see also /usr/share/applications

# Launchbar Click Actions
# Define starter commands for left and right single click
# Leave blank if you won't start any app with this click

# AudioVideo
#starter: audio01 audio02 audio03-
audio01_left = spotify &
audio01_right =
audio02_left = audacity &
audio02_right =
audio03_left =
audio03_right =
#starter: video01 video02 video03-
video01_left = mpv &
video01_right = vlc &
video02_left = obs-studio &
video02_right =
video03_left =
video03_right =

# DesktopSettings
#starter: settings01 bluetooth01 net01 printer01
settings01_left =
settings01_right =
bluetooth01_left = blueman-manager &
bluetooth01_right = pavucontrol &
net01_left = nm-connection-editor &
net01_right =
printer01_left = xdg-open http://localhost:631 &
printer01_right =

# Development
#starter: d_tool01
d_tool01_left =
d_tool01_right =

# Education

# Games
#starter: dosb0x01 games01 games02
games01_left =
games01_right =
games02_left =
games02_right =
#obsolete
dosbox01_left =
dosbox01_right =

# Graphics
#starter: scan01 pic01
scan01_left = simple-scan &
scan01_right =
pic01_left = gimp &
pic01_right = libreoffice --draw &

# Internet
#starter: web01 mail01 download01 messenger01
web01_left = firefox &
web01_right = chromium &
mail01_left = thunderbird &
mail01_right = xdg-open https://mail.google.com &
download01_left = uget-gtk &
download01_right =
messenger01_left = hexchat &
messenger01_right =

# Multimedia

# Office
#starter: calendar01 pdftool01
calendar01_left = xdg-open https://calendar.google.com/calendar &
calendar01_right =
pdftool01_left = pdfarranger &
pdftool01_right =
#starter: office01 office02 office03 office04
office01_left = libreoffice --writer &
office01_right = libreoffice --calc &
office02_left =
office02_right =
office03_left =
office03_right =
office04_left =
office04_right =

# Other
#starter: other01
other01_left =
other01_right =

# System
#starter: fm01 fm02 fm03 fm04
fm01_left = $_USERSCRIPT/launch_fm_home.sh &
fm01_right =
fm02_left = $_USERSCRIPT/launch_fm_emc.sh &
fm02_right =
fm03_left = thunar &
fm03_right =
fm04_left =
fm04_right =
#starter: terminal01 terminal02
terminal01_left = lxterminal &
terminal01_right =
terminal02_left =
terminal02_right =
#starter: package01 package02
package01_left =
package01_right =
package02_left = $_BASEDIR/install/EMC_standalone_app_installer.sh &
package02_right = synaptic-pkexec &
#starter: emu01 emu02
emu01_left =
emu01_right =
emu02_left =
emu02_right =
#starter: hw01
hw01_left = $_SCRIPTDIR/hwinfo.sh &
hw01_right = hardinfo &

# Utility
#starter: editor01 editor02
editor01_left = mousepad &
editor01_right = geany &
editor02_left =
editor02_right =
#starter: calculator01 search01 disk01
calculator01_left = galculator &
calculator01_right =
search01_left = catfish &
search01_right = xfce4-appfinder &
disk01_left = gnome-disks &
disk01_right =

# Special User Apps
#starter: user01 user02 user03 user04 user05

# NOTE: Use simple commands here (e.g., /path/to/app --option).
# DO NOT use pipes (|) or logical operators (&&, ||). 
# For complex commands, point to a .sh file instead.

# However, complex paths or options are processed properly. Examples:
# user01_left = /usr/lib/virtualbox/VirtualBoxVM --comment WindowsXP_Music --startvm {e7d074d8-6d4f-43a9-a9bc-2e8c01f42345}
# user01_left = VBoxManage startvm WindowsXP_Music --type sdl
# user01_left = VBoxSDL -startvm WindowsXP_Music
# user01_right = /usr/lib/virtualbox/VirtualBoxVM --comment Ubuntu_10.04 --startvm {b64a6ef0-a1a9-4fe2-83ca-046a80d8847e}
# user01_right = VBoxManage startvm Ubuntu_10.04 --type sdl
# user01_right = VBoxSDL -startvm Ubuntu_10.04
# user02_left = /mnt/linuxdata01/genymotion/player --vm-name "Google Pixel 2"

user01_left =
user01_right =
user02_left =
user02_right =
user03_left =
user03_right =
user04_left =
user04_right =
user05_left =

[user-files]
# Quick file access
# Note: Paths can use $HOME, ${HOME} or ~/ to refer to your home directory.
# Other environment variables are NOT supported in this config.
# Use absolute path instead

file01 =
file01_alt =
file02 =
file02_alt =
file03 =
file03_alt =
file04 = $HOME/.config/i3/usr/config_workspaces
file04_alt = $HOME/.config/i3/usr/config_usercommands
file05 = $HOME/.bash_history
file05_alt = $HOME/.config/i3/usr/i3_Reference_Card.pdf

[ws-script]
# Execute script or app on workspace start
# you can use $_USERSCRIPT to acces your scripts in $HOME/.config/polybar/i3/usr/script
# leave blank if no start script is required.
s_ws1 = $_USERSCRIPT/launch_fm_home.sh &
s_ws2 = spotify &
s_ws3 =
s_ws4 =
s_ws5 =
s_ws6 = $_USERSCRIPT/launch_fm_emc.sh &
s_ws7 = pcmanfm -n $_BASEDIR &
s_ws8 =
s_ws9 =
s_ws10 = pcmanfm -n $HOME &
