# icons.ini edit for your needs

# Icons for your launchbars. Note: icons may still cause warnings 
# if your Nerd Font version doesn't support it.

# for more icons look here: https://www.nerdfonts.com/cheat-sheet

# every icon can trigger a click-left or a click-right event
# so that you can start 2 applications per icon

# same starters as in applications.ini but prefixed with i_

# categories like xfce4 appfinder
# see also /usr/share/applications

[icons-launch]

#AudioVideo
i_audio01 = 󱀞
i_audio02 = 󰲸
i_audio03 = 
i_video01 = 󰕧
i_video02 = 󰯜
i_video03 = 󰃽

# DesktopSettings
i_settings01 = 
i_bluetooth01 = 
i_net01 = 󰩠
i_printer01 = 󰐪

# Development
# yad icon browser
i_d_tool01 = 

# Education

# Games
i_dosbox01 = 

# Graphics
i_scan01 = 󰚫
i_pic01 = 

# Internet
i_web01 = 󰖟
i_web02 = 󰾔
i_mail01 = 󰛮
i_download01 = 
i_messenger01 = 󰍩

# Multimedia

# Office
i_calendar01 = 
i_pdftool01 = 󰈦
i_office01 = 
i_office02 = 
i_office03 = 
i_office04 = 

# Other
i_other01 = 󰗵

# System 
i_fm01 = 󱑿
i_fm02 = 󱑾
i_fm03 = 
i_fm04 = 
i_terminal01 = 
i_terminal02 = 
i_package01 = 󰏖
i_package02 = 󰏗
i_emu01 = 
i_emu02 = 
i_hw01 = 

# Utility
i_editor01 = 󱩽
i_editor02 = 󱩼
i_calculator01 = 
i_search01  = 
i_disk01 = 󰋊

# Special User Icons
i_user01 = 󰨡
i_user02 = 
i_user03 =
i_user04 =
i_user05 =

i_WinXP = 󰨡
i_androidx86 = 
i_Ubuntu_10 = 

[icons-files]
# files
i_file01 = 󰈣1
i_file02 = 2
i_file03 = 3
i_file04 = 󱀾4
i_file05 = 5

[icons-other]
#i_launch01 = 󱎯
# this is a hack to minimize polybar movements
#i_launch01 = 󰄮󰄮
#i_launch01 = 
i_launch01 = 󰅮󰅬

#do not change this, generated by script
[icons-ws]
i_ws_01 = 󰋜
i_ws_02 = 󰽯
i_ws_03 = 󰽯 2
i_ws_04 = 
i_ws_05 =  2
i_ws_06 = EMC
i_ws_07 = PROGRAMMING
i_ws_08 = 8
i_ws_09 = 9
i_ws_10 = 󰶆
