# tooltips for your launchbar, edit for your needs
#STANDALONE EMC Version

#You can copy the entries from applications.ini, but you must prefix them with a t_.!!!
#If you leave it blank, the tooltip “click-right: not implemented” will appear.

[tooltip-launch]
# categories like xfce4 appfinder but no duplicate keys
# see also /usr/share/applications

#AudioVideo
t_audio01_left = spotify
t_audio01_right =
t_audio02_left = audacity
t_audio02_right =
t_audio03_left =
t_audio03_right =

t_video01_left = mpv
t_video01_right = vlc
t_video02_left = obs-studio
t_video02_right =
t_video03_left =
t_video03_right =

# DesktopSettings
t_settings01_left =
t_settings01_right =
t_bluetooth01_left = blueman-manager
t_bluetooth01_right =pavucontrol
t_net01_left = nm-connection-editor
t_net01_right =
t_printer01_left = open cups in browser
t_printer01_right = system-config-printer

# Development
t_d_tool01_left =
t_d_tool01_right =

# Education

# Games
t_dosbox01_left =
t_dosbox01_right =

# Graphics
t_scan01_left = simple-scan
t_scan01_right =
t_pic01_left = gimp
t_pic01_right = libreoffice draw

# Internet
t_web01_left = firefox
t_web01_right = chromium
t_mail01_left = thunderbird
t_mail01_right = google mail
t_download01_left = uget-gtk
t_download01_right =
t_messenger01_left = hexchat
t_messenger01_right =

# Multimedia

# Office
t_calendar01_left = open google calendar in browser
t_calendar01_right =
t_pdftool01_left = pdfarranger
t_pdftool01_right =

t_office01_left = libreoffice writer
t_office01_right = libreoffice calc
t_office02_left =
t_office02_right =
t_office03_left =
t_office03_right =
t_office04_left =
t_office04_right =

# Other
t_other01_left =
t_other01_right =

# System
t_fm01_left = launch pcmanfm with standard directories
t_fm01_right =
t_fm02_left = launch pcmanfm with EMC directories
t_fm02_right =
t_fm03_left = launch thunar
t_fm03_right =
t_fm04_left =
t_fm04_right =

t_terminal01_left = lxterminal
t_terminal01_right =
t_terminal02_left =
t_terminal02_right =

t_package01_left = synaptic-pkexec
t_package01_right =
t_package02_left = EMC_standalone_app_installer
t_package02_right = synaptic-pkexec

t_emu01_left =
t_emu01_right =
t_emu02_left =
t_emu02_right =

t_hw01_left = hwinfo.sh
t_hw01_right = hardinfo

# Utility
t_editor01_left = mousepad
t_editor01_right = geany
t_editor02_left =
t_editor02_right =

t_calculator01_left = galculator
t_calculator01_right =
t_search01_left = catfish
t_search01_right = xfce4-appfinder
t_disk01_left = gnome-disks
t_disk01_right =

# Special User Apps
t_user01_left =
t_user01_right =
t_user02_left =
t_user02_right =
t_user03_left =
t_user03_right =
t_user04_left =
t_user04_right =
t_user05_left =
t_user05_right =

[tooltip-files]
# file opener in center launchbar
t_file01 =
t_file01_alt =
t_file02 =
t_file02_alt =
t_file03 =
t_file03_alt =
t_file04 = edit config_workspaces
t_file04_alt = edit config_usercommands
t_file05 = edit bash history
t_file05_alt = show i3 keybinding reference

#do not change this, generated by script
[tooltip-ws]
t_ws_1 = open workspace 󰋜
t_ws_2 = open workspace 󰽯
t_ws_3 = open workspace 󰽯 2
t_ws_4 = open workspace 
t_ws_5 = open workspace  2
t_ws_6 = open workspace EMC
t_ws_7 = open workspace PROGRAMMING
t_ws_8 = open workspace 8
t_ws_9 = open workspace 9
t_ws_10 = open workspace 󰶆
