# main bar specifications

[bar/main_base]

inherit = fonts

bottom = true

width = 100%
height = ${monitor-data.mainbar_height}
radius = 6

dpi = 0

background = ${colors.background}
foreground = ${colors.foreground}

font-0 = ${monitor-data.mainbar_font_0}
font-1 = ${monitor-data.mainbar_font_1}

line-size = 3pt

border-size = 1pt
border-color = ${colors.border}

padding-left = 0
padding-right = 0

module-margin = 0

# Temporary separator for module alignment and debugging
;separator = |
separator-foreground = ${colors.disabled}

cursor-click = pointer
cursor-scroll = ns-resize

locale = ${app-data.locale}

enable-ipc = true

fixed-center = true
override-redirect = false

# Mouse scroll actions to toggle launchbar
scroll-up = "$_SCRIPTDIR/show_launchbar.sh c"
scroll-down = "$_SCRIPTDIR/hide_launchbar.sh"

[bar/main_i3]

inherit = bar/main_base

click-left = "$_i3_SCRIPTDIR/i3_info_mainbar.sh left"
click-right = "$_i3_SCRIPTDIR/i3_info_mainbar.sh right"
double-click-left = "$_SCRIPTDIR/emc_toolbar.sh"

double-click-interval = 400

### DO NOT EDIT THIS ###
# workspace and file access
modules-left = i3_workspaces i3_windows
#modules-left = 
modules-center = i3_scratch i3_move_left i3_move_right i3_move_up i3_move_down i3_move_to i3_win i3_ws
modules-right = ${app-main.main_modules_right}
### DO NOT EDIT THIS ###
