# configuration for all launch-and tooltip bars

[bar/launchbar_base]
inherit = fonts

width = ${monitor-data.launchbar_width}
height = ${monitor-data.launchbar_height}
dpi = 0

offset-y = ${monitor-data.launchbar_offset_y}
radius = 10
bottom = false

background = ${colors.background}
foreground = ${colors.foreground}

font-0 = ${monitor-data.launchbar_font_0}
font-1 = ${monitor-data.launchbar_font_1}

border-size = 1pt
border-color = ${colors.border}

padding-left = 0
padding-right = 0

module-margin = 0

# Temporary separator for module alignment and debugging
;separator = |
separator-foreground = ${colors.disabled}

fixed-center = true

cursor-click = pointer

# DO NOT enable wm-restack for i3 in this setup.
# Enabling it may cause the bar to become invisible or non-functional.
; wm-restack = i3
override-redirect = true
enable-ipc = true

[bar/launchbar_center]
inherit = bar/launchbar_base

width = ${monitor-data.launchbar_center_width}
offset-x = ${monitor-data.launchbar_center_offset_x}

# workspace and file access
modules-left =  launchbar_spacebase launch_file_05 launch_file_04 launch_file_03 launch_file_02 launch_file_01 launchbar_dblspace launch_i3_ws08 launch_i3_ws06 launch_i3_ws04 launch_i3_ws02 launch_i3_ws_01
# switches launchbar center and launchbar left or right
modules-center = launch_bar 
# app starters - edit in applications.ini
modules-right = ${app-launch.launchbar_center_modules_right}

click-left = "$_i3_SCRIPTDIR/i3_info_launchbar.sh left"
click-right = "$_i3_SCRIPTDIR/i3_info_launchbar.sh right"
# no double-click events; launchers cannot intercept them!
# double-click-left = "$_SCRIPTDIR/emc_toolbar.sh"

[bar/tooltips_center]
inherit = bar/launchbar_center

foreground = ${colors.tooltips-foreground}
background = ${colors.tooltips-background}

modules-left = 
modules-center = launchbar_tooltip
modules-right = 

click-left = kill $(cat /tmp/polybar_tooltips.pid) 2>/dev/null

[bar/launchbar_left]
inherit = bar/launchbar_base

offset-x = ${monitor-data.launchbar_left_offset_x}

# app starters - edit in applications.ini
modules-left = ${app-launch.launchbar_left_modules_left}
modules-right = ${app-launch.launchbar_left_modules_right}
# switches launchbar left and launchbar center
modules-center = launch_bar_center

click-left = "$_i3_SCRIPTDIR/i3_info_launchbar.sh left"
click-right = "$_i3_SCRIPTDIR/i3_info_launchbar.sh right"

[bar/tooltips_left]
inherit = bar/launchbar_left

foreground = ${colors.tooltips-foreground}
background = ${colors.tooltips-background}

modules-left = 
modules-center = launchbar_tooltip
modules-right = 

click-left = kill $(cat /tmp/polybar_tooltips.pid) 2>/dev/null

[bar/launchbar_right]
inherit = bar/launchbar_base

offset-x = ${monitor-data.launchbar_right_offset_x}

# app starters - edit in applications.ini
modules-left = ${app-launch.launchbar_right_modules_left}
modules-right = ${app-launch.launchbar_right_modules_right}
# switches launchbar right and launchbar center
modules-center = launch_bar_center

click-left = "$_i3_SCRIPTDIR/i3_info_launchbar.sh left"
click-right = "$_i3_SCRIPTDIR/i3_info_launchbar.sh right"

[bar/tooltips_right]
inherit = bar/launchbar_right

foreground = ${colors.tooltips-foreground}
background = ${colors.tooltips-background}

modules-left = 
modules-center = launchbar_tooltip
modules-right = 

click-left = kill $(cat /tmp/polybar_tooltips.pid) 2>/dev/null
