;
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[colors]
background = #282A2E
background-alt = #373B41
foreground = #C5C8C6
foreground-alt = #151816
primary = #F0C674
secondary = #8ABEFF
tertiary = #9ABEB7
alert = #A54242
safe = #42A542
disabled = #707880
border = #FFFFFF

# Format: #AARRGGBB
background-transparent = #cc282A2E
background-light_transparent = #33282A2E
tooltips-foreground=${colors.foreground}
tooltips-background=${colors.background-alt}

[fonts]
font-0 = Symbols Nerd Font Mono:style=Regular:size=12;2
font-1 = Noto Sans:size=12;2
font-2 = DejaVu Sans Mono;2

include-file = usr/applications.ini
include-file = usr/tooltips.ini
include-file = usr/icons.ini
include-file = usr/monitor.ini
include-file = bar_main.ini
include-file = bar_launch.ini
include-file = main_modules.ini
include-file = launchbar_app_modules.ini
include-file = launchbar_workspace_modules.ini
include-file = i3/i3_controls.ini
include-file = internal_modules.ini

[settings]
screenchange-reload = true
pseudo-transparency = true
;double-click-interval = 400
# native filemanager do not edit!
EMC_FM = pcmanfm


