# internal modules in alphabetical order

# changed
[module/cpu]
type = internal/cpu
interval = 2

label = %percentage:2%%
format = %{A1:$_SCRIPTDIR/info_cpu.sh left:}%{A6:$_SCRIPTDIR/info_cpu.sh dbl_left:}%{A3:$_SCRIPTDIR/info_cpu.sh right:}%{A8: :}%{A4: :}%{A5: :} <label>  %{A}%{A}%{A}%{A}%{A}%{A}

format-prefix = %{A1:$_SCRIPTDIR/event_cpu.sh left:}%{A6:$_SCRIPTDIR/event_cpu.sh dbl_left:}%{A3:$_SCRIPTDIR/event_cpu.sh right:}%{A8:$_SCRIPTDIR/event_cpu.sh dbl_right:}%{A4:$_SCRIPTDIR/event_cpu.sh up:}%{A5:$_SCRIPTDIR/event_cpu.sh down:}%{A}%{A}%{A}%{A}%{A}%{A}
format-prefix-foreground = ${colors.primary}

# changed
[module/date]
type = internal/date
interval = 10

date = "%H:%M"

label = %date%
format = %{A1:$_SCRIPTDIR/info_date.sh left:}%{A6: :}%{A3:$_SCRIPTDIR/info_date.sh right:}%{A8: :}%{A4: :}%{A5: :} <label>  %{A}%{A}%{A}%{A}%{A}%{A}

format-prefix = %{A1:$_SCRIPTDIR/event_date.sh left:}%{A6:$_SCRIPTDIR/event_date.sh dbl_left:}%{A3:$_SCRIPTDIR/event_date.sh right:}%{A8:$_SCRIPTDIR/event_date.sh dbl_right:}%{A4:$_SCRIPTDIR/event_date.sh up:}%{A5:$_SCRIPTDIR/event_date.sh down:}%{A}%{A}%{A}%{A}%{A}%{A}
format-prefix-foreground = ${colors.primary}

# changed
[module/eth]
inherit = network-base
interface-type = wired

label-connected = "ON"
format-connected = %{A1:$_SCRIPTDIR/info_eth.sh left:}%{A6:$_SCRIPTDIR/info_eth.sh dbl_left:}%{A3:$_SCRIPTDIR/info_eth.sh right :}%{A8: :}%{A4: :}%{A5: :} <label-connected>  %{A}%{A}%{A}%{A}%{A}%{A}

format-connected-prefix = %{A1:$_SCRIPTDIR/event_eth.sh left:}%{A6:$_SCRIPTDIR/event_eth.sh dbl_left:}%{A3:$_SCRIPTDIR/event_eth.sh right:}%{A8:$_SCRIPTDIR/event_eth.sh dbl_right:}%{A4:$_SCRIPTDIR/event_eth.sh up:}%{A5:$_SCRIPTDIR/event_eth.sh down:}󰈀%{A}%{A}%{A}%{A}%{A}%{A}
format-connected-prefix-foreground = ${colors.primary}

label-disconnected = "OFF"
format-disconnected = %{A1:$_SCRIPTDIR/info_eth.sh left:}%{A6:$_SCRIPTDIR/info_eth.sh dbl_left:}%{A3:$_SCRIPTDIR/info_eth.sh right :}%{A8: :}%{A4: :}%{A5: :} <label-disconnected>  %{A}%{A}%{A}%{A}%{A}%{A}

format-disconnected-prefix = %{A1:$_SCRIPTDIR/event_eth.sh left:}%{A6:$_SCRIPTDIR/event_eth.sh dbl_left:}%{A3:$_SCRIPTDIR/event_eth.sh right:}%{A8:$_SCRIPTDIR/event_eth.sh dbl_right:}%{A4:$_SCRIPTDIR/event_eth.sh up :}%{A5:$_SCRIPTDIR/event_eth.sh down:}󰈀%{A}%{A}%{A}%{A}%{A}%{A}
format-disconnected-prefix-foreground = ${colors.disabled}

#changed
[module/filesys]
type = internal/fs
interval = 25

mount-0 = ${app-data.filesys_mount}

label-mounted = %mountpoint% %percentage_used%%
format-mounted = %{A1:$_SCRIPTDIR/info_filesys.sh left:}%{A6:$_SCRIPTDIR/info_filesys.sh dbl_left:}%{A3:$_SCRIPTDIR/info_filesys.sh right:}%{A8:$_SCRIPTDIR/info_filesys.sh dbl_right:}%{A4: :}%{A5: :} <label-mounted> %{A}%{A}%{A}%{A}%{A}%{A}

format-mounted-prefix = %{A1:$_SCRIPTDIR/event_filesys.sh left:}%{A6:$_SCRIPTDIR/event_filesys.sh dbl_left:}%{A3:$_SCRIPTDIR/event_filesys.sh right:}%{A8:$_SCRIPTDIR/event_filesys.sh dbl_right:}%{A4:$_SCRIPTDIR/event_filesys.sh up:}%{A5:$_SCRIPTDIR/event_filesys.sh down:}󰋊%{A}%{A}%{A}%{A}%{A}%{A}
format-mounted-prefix-foreground = ${colors.primary}

label-unmounted = %mountpoint%
label-unmounted-foreground = ${colors.disabled}
format-unmounted = %{A1:$_SCRIPTDIR/info_filesys.sh left:}%{A6:$_SCRIPTDIR/info_filesys.sh dbl_left:}%{A3:$_SCRIPTDIR/info_filesys.sh right:}%{A8:$_SCRIPTDIR/info_filesys.sh dbl_right:}%{A4: :}%{A5: :} <label-unmounted> %{A}%{A}%{A}%{A}%{A}%{A}

;format-unmounted-prefix = %{A1:$_SCRIPTDIR/event_filesys.sh left:}%{A3:$_SCRIPTDIR/event_filesys.sh right:}%{A4: :}%{A5: :}󰋊%{A}%{A}%{A}%{A}
format-unmounted-prefix = %{A1:$_SCRIPTDIR/event_filesys.sh left:}%{A6:$_SCRIPTDIR/event_filesys.sh dbl_left:}%{A3:$_SCRIPTDIR/event_filesys.sh right:}%{A8:$_SCRIPTDIR/event_filesys.sh dbl_right:}%{A4:$_SCRIPTDIR/event_filesys.sh up:}%{A5:$_SCRIPTDIR/event_filesys.sh down:}󰋊%{A}%{A}%{A}%{A}%{A}%{A}
format-unmounted-prefix-foreground = ${colors.disabled}

# changed
[module/keyboard]
type = internal/xkeyboard

format = %{A1:$_SCRIPTDIR/info_keyboard.sh left:}%{A6: :}%{A3:$_SCRIPTDIR/info_keyboard.sh right:}%{A8: :}%{A4: :}%{A5: :} <label-layout><label-indicator>  %{A}%{A}%{A}%{A}%{A}%{A}
format-spacing = 1

label-layout = %layout%
label-layout-foreground = ${colors.foreground}

label-indicator-on-capslock = 󰌌
label-indicator-on-capslock-foreground = ${colors.foreground}

label-indicator-off-capslock = 
label-indicator-off-capslock-foreground = ${colors.disabled}

label-indicator-on-numlock = 
label-indicator-on-numlock-foreground = ${colors.foreground}

label-indicator-off-numlock = 
label-indicator-off-numlock-foreground = ${colors.disabled}

;format-prefix = %{A1:$_SCRIPTDIR/event_keyboard.sh left:}%{A3:$_SCRIPTDIR/event_keyboard.sh right:}%{A4: :}%{A5: :}󰧺%{A}%{A}%{A}%{A}
format-prefix = %{A1:$_SCRIPTDIR/event_keyboard.sh left:}%{A6:$_SCRIPTDIR/event_keyboard.sh dbl_left:}%{A3:$_SCRIPTDIR/event_keyboard.sh right:}%{A8:$_SCRIPTDIR/event_keyboard.sh dbl_right:}%{A4:$_SCRIPTDIR/event_keyboard.sh up:}%{A5:$_SCRIPTDIR/event_keyboard.sh down:}󰧺%{A}%{A}%{A}%{A}%{A}%{A}
format-prefix-foreground = ${colors.primary}

#changed
[module/memory]
type = internal/memory
interval = 2

label = %percentage_used:2%%
format = %{A1:$_SCRIPTDIR/info_memory.sh left:}%{A6:$_SCRIPTDIR/info_memory.sh dbl_left:}%{A3:$_SCRIPTDIR/info_memory.sh right:}%{A8: :}%{A4: :}%{A5: :} <label>  %{A}%{A}%{A}%{A}%{A}%{A}

;format-prefix = %{A1:$_SCRIPTDIR/event_memory.sh left:}%{A3:$_SCRIPTDIR/event_memory.sh right:}%{A4: :}%{A5: :}󰘚%{A}%{A}%{A}%{A}
format-prefix = %{A1:$_SCRIPTDIR/event_memory.sh left:}%{A6:$_SCRIPTDIR/event_memory.sh dbl_left:}%{A3:$_SCRIPTDIR/event_memory.sh right:}%{A8:$_SCRIPTDIR/event_memory.sh dbl_right:}%{A4:$_SCRIPTDIR/event_memory.sh up:}%{A5:$_SCRIPTDIR/event_memory.sh down:}󰘚%{A}%{A}%{A}%{A}%{A}%{A}
format-prefix-foreground = ${colors.primary}

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = %{F#F0C674}%ifname%%{F#707880} disconnected

# changed
[module/pulseaudio]
type = internal/pulseaudio

label-volume =  %percentage%%
format-volume = %{A1:$_SCRIPTDIR/info_pulseaudio.sh left:}%{A6:$_SCRIPTDIR/info_pulseaudio.sh dbl_left:}%{A3:$_SCRIPTDIR/info_pulseaudio.sh right:}%{A8:$_SCRIPTDIR/info_pulseaudio.sh dbl_right:} <label-volume>  %{A}%{A}%{A}%{A}

;format-volume-prefix = %{A1:$_SCRIPTDIR/event_pulseaudio.sh left:}%{A3:$_SCRIPTDIR/event_pulseaudio.sh right:}%{A}%{A}
format-volume-prefix = %{A1:$_SCRIPTDIR/event_pulseaudio.sh left:}%{A6:$_SCRIPTDIR/event_pulseaudio.sh dbl_left:}%{A3:$_SCRIPTDIR/event_pulseaudio.sh right:}%{A8:$_SCRIPTDIR/event_pulseaudio.sh dbl_right:}%{A4:$_SCRIPTDIR/event_pulseaudio.sh up:}%{A5:$_SCRIPTDIR/event_pulseaudio.sh down:}%{A}%{A}%{A}%{A}%{A}%{A}
format-volume-prefix-foreground = ${colors.primary}

label-muted =  " OFF"
format-muted = %{A1:$_SCRIPTDIR/info_pulseaudio.sh left:}%{A6:$_SCRIPTDIR/info_pulseaudio.sh dbl_left:}%{A3:$_SCRIPTDIR/info_pulseaudio.sh right:}%{A8:$_SCRIPTDIR/info_pulseaudio.sh dbl_right:} <label-muted>  %{A}%{A}%{A}%{A}
format-muted-foreground = ${colors.disabled}

#format-muted-prefix = %{A1:$_SCRIPTDIR/event_pulseaudio.sh left:}%{A3:$_SCRIPTDIR/event_pulseaudio.sh right:}%{A4:$_SCRIPTDIR/event_pulseaudio.sh up:}%{A5: :}%{A}%{A}%{A}%{A}
format-muted-prefix = %{A1:$_SCRIPTDIR/event_pulseaudio.sh left:}%{A6: :}%{A3:$_SCRIPTDIR/event_pulseaudio.sh right:}%{A8: :}%{A4:$_SCRIPTDIR/event_pulseaudio.sh up:}%{A5:$_SCRIPTDIR/event_pulseaudio.sh down:}%{A}%{A}%{A}%{A}%{A}%{A}
format-muted-prefix-foreground = ${colors.disabled}

# changed
[module/wlan]
inherit = network-base
interface-type = wireless

label-connected = " ON"
format-connected = %{A1:$_SCRIPTDIR/info_wlan.sh left:}%{A6:$_SCRIPTDIR/info_wlan.sh dbl_left:}%{A3:$_SCRIPTDIR/info_wlan.sh right:}%{A8: :}%{A4: :}%{A5: :} <label-connected>  %{A}%{A}%{A}%{A}%{A}%{A}

;format-connected-prefix = %{A1:$_SCRIPTDIR/event_wlan.sh left:}%{A3:$_SCRIPTDIR/event_wlan.sh right:}%{A4: :}%{A5: :}󰖩%{A}%{A}%{A}%{A}
format-connected-prefix = %{A1:$_SCRIPTDIR/event_wlan.sh left:}%{A6:$_SCRIPTDIR/event_wlan.sh dbl_left:}%{A3:$_SCRIPTDIR/event_wlan.sh right:}%{A8:$_SCRIPTDIR/event_wlan.sh dbl_right:}%{A4:$_SCRIPTDIR/event_wlan.sh up:}%{A5:$_SCRIPTDIR/event_wlan.sh down:}󰖩%{A}%{A}%{A}%{A}%{A}%{A}
format-connected-prefix-foreground = ${colors.primary}

label-disconnected = " OFF"
format-disconnected = %{A1:$_SCRIPTDIR/info_wlan.sh left:}%{A6:$_SCRIPTDIR/info_wlan.sh dbl_left:}%{A3:$_SCRIPTDIR/info_wlan.sh right:}%{A8: :}%{A4: :}%{A5: :} <label-disconnected>  %{A}%{A}%{A}%{A}%{A}%{A}

;format-disconnected-prefix = %{A1:$_SCRIPTDIR/event_wlan.sh left:}%{A3:$_SCRIPTDIR/event_wlan.sh right:}%{A4: :}%{A5: :}󰖩%{A}%{A}%{A}%{A}
format-disconnected-prefix = %{A1:$_SCRIPTDIR/event_wlan.sh left:}%{A6:$_SCRIPTDIR/event_wlan.sh dbl_left:}%{A3:$_SCRIPTDIR/event_wlan.sh right:}%{A8:$_SCRIPTDIR/event_wlan.sh dbl_right:}%{A4:$_SCRIPTDIR/event_wlan.sh up:}%{A5:$_SCRIPTDIR/event_wlan.sh down:}󰖩%{A}%{A}%{A}%{A}%{A}%{A}
format-disconnected-prefix-foreground = ${colors.disabled}
