;launchbar modules config for app starters
;use in launchbar_left, launchbar_center or launchbar_right 

### basic modules ###

[module/launchbar_tooltip]
type = custom/script

# show the tooltip in /tmp/polybar_tooltip
exec = cat /tmp/polybar_tooltip 2>/dev/null
# delete lock file 
click-left = kill $(cat /tmp/polybar_tooltips.pid) 2>/dev/null

[module/launchbar_spacebase]
type = custom/text

label = " "

format = <label>

[module/launchbar_dblspace]
inherit = module/launchbar_spacebase

format-padding = 1


[module/launch_base]
type = custom/text

# This ensures symmetry and keeps the click/scroll area stable.
# use font 2
;label = " %{T2}%label%%{T-} "
label = " %label% "
label-maxlen = 3
label-ellipsis = false

# Remove any leading space from format since it's now inside the label
# format = "<label>"
format = "  <label>  "

format-foreground = ${colors.primary}
format-padding = 0

click-left = notify-send -t 2000 "launch_base: click-left not implemented"
click-right = notify-send -t 2000 "launch_base: click-right not implemented"
scroll-up = $_SCRIPTDIR/tooltip.sh "click left: not implemented"
scroll-down = $_SCRIPTDIR/tooltip.sh "click right: not implemented"

# Depending on click, this module can launch either the right or the left launcher bar.
[module/launch_bar]
inherit = module/launch_base

label = ${icons-other.i_launch01}
format-foreground = ${colors.safe}

click-left = sh -c "$_SCRIPTDIR/hide_launchbar.sh && $_SCRIPTDIR/show_launchbar.sh l"
click-right = sh -c "$_SCRIPTDIR/hide_launchbar.sh && $_SCRIPTDIR/show_launchbar.sh r"
scroll-up = $_SCRIPTDIR/tooltip.sh "click left: show left launchbar"
scroll-down = $_SCRIPTDIR/tooltip.sh "click right: show right launchbar"

# This module can only launch the central launchbar, regardless of using right or left mouse button.
[module/launch_bar_center]
inherit = module/launch_base

label = ${icons-other.i_launch01}
format-foreground = ${colors.safe}

click-left = sh -c "$_SCRIPTDIR/hide_launchbar.sh && $_SCRIPTDIR/show_launchbar.sh"
click-right = sh -c "$_SCRIPTDIR/hide_launchbar.sh && $_SCRIPTDIR/show_launchbar.sh"
scroll-up = $_SCRIPTDIR/tooltip.sh "click left: show center launchbar"
scroll-down = $_SCRIPTDIR/tooltip.sh "click right: show center launchbar"

### app starter ###

# categories like xfce4 appfinder

#AudioVideo

[module/audio01]
inherit = module/launch_base

label = ${icons-launch.i_audio01}

click-left = $_SCRIPTDIR/event_launchbar.sh audio01_left &
click-right =$_SCRIPTDIR/event_launchbar.sh audio01_right &
scroll-up = $_SCRIPTDIR/tooltip.sh t_audio01_left up &
scroll-down = $_SCRIPTDIR/tooltip.sh t_audio01_right down &

[module/audio02]
inherit = module/launch_base

label = ${icons-launch.i_audio02}

click-left = $_SCRIPTDIR/event_launchbar.sh audio02_left &
click-right =$_SCRIPTDIR/event_launchbar.sh audio02_right &
scroll-up = $_SCRIPTDIR/tooltip.sh t_audio02_left up &
scroll-down = $_SCRIPTDIR/tooltip.sh t_audio02_right down &

[module/audio03]
inherit = module/launch_base

label = ${icons-launch.i_audio03}

click-left = $_SCRIPTDIR/event_launchbar.sh audio03_left &
click-right =$_SCRIPTDIR/event_launchbar.sh audio03_right &
scroll-up = $_SCRIPTDIR/tooltip.sh t_audio03_left up &
scroll-down = $_SCRIPTDIR/tooltip.sh t_audio03_right down &

[module/video01]
inherit = module/launch_base

label = ${icons-launch.i_video01}

click-left = $_SCRIPTDIR/event_launchbar.sh video01_left &
click-right =$_SCRIPTDIR/event_launchbar.sh video01_right &
scroll-up = $_SCRIPTDIR/tooltip.sh t_video01_left up &
scroll-down = $_SCRIPTDIR/tooltip.sh t_video01_right down &

[module/video02]
inherit = module/launch_base

label = ${icons-launch.i_video02}

click-left = $_SCRIPTDIR/event_launchbar.sh video02_left &
click-right =$_SCRIPTDIR/event_launchbar.sh video02_right &
scroll-up = $_SCRIPTDIR/tooltip.sh t_video02_left up &
scroll-down = $_SCRIPTDIR/tooltip.sh t_video02_right down &

[module/video03]
inherit = module/launch_base

label = ${icons-launch.i_video03}

click-left = $_SCRIPTDIR/event_launchbar.sh video03_left &
click-right =$_SCRIPTDIR/event_launchbar.sh video03_right &
scroll-up = $_SCRIPTDIR/tooltip.sh t_video03_left up &
scroll-down = $_SCRIPTDIR/tooltip.sh t_video03_right down &

# DesktopSettings

[module/settings01]
inherit = module/launch_base

label = ${icons-launch.i_settings01}

click-left = $_SCRIPTDIR/event_launchbar.sh settings01_left &
click-right =$_SCRIPTDIR/event_launchbar.sh settings01_right &
scroll-up = $_SCRIPTDIR/tooltip.sh t_settings01_left up &
scroll-down = $_SCRIPTDIR/tooltip.sh t_settings01_right down &

[module/bluetooth01]
inherit = module/launch_base

label = ${icons-launch.i_bluetooth01}

click-left = $_SCRIPTDIR/event_launchbar.sh bluetooth01_left &
click-right =$_SCRIPTDIR/event_launchbar.sh bluetooth01_right &
scroll-up = $_SCRIPTDIR/tooltip.sh t_bluetooth01_left up &
scroll-down = $_SCRIPTDIR/tooltip.sh t_bluetooth01_right down &

[module/net01]
inherit = module/launch_base

label = ${icons-launch.i_net01}

click-left = $_SCRIPTDIR/event_launchbar.sh net01_left &
click-right =$_SCRIPTDIR/event_launchbar.sh net01_right &
scroll-up = $_SCRIPTDIR/tooltip.sh t_net01_left up &
scroll-down = $_SCRIPTDIR/tooltip.sh t_net01_right down &

[module/printer01]
inherit = module/launch_base

label = ${icons-launch.i_printer01}

click-left = $_SCRIPTDIR/event_launchbar.sh printer01_left &
click-right =$_SCRIPTDIR/event_launchbar.sh printer01_right &
scroll-up = $_SCRIPTDIR/tooltip.sh t_printer01_left up &
scroll-down = $_SCRIPTDIR/tooltip.sh t_printer01_right down &

# Development
[module/d_tool01]
inherit = module/launch_base

label = ${icons-launch.i_d_tool01}

click-left = $_SCRIPTDIR/event_launchbar.sh d_tool01_left &
click-right =$_SCRIPTDIR/event_launchbar.sh d_tool01_right &
scroll-up = $_SCRIPTDIR/tooltip.sh t_d_tool01_left up &
scroll-down = $_SCRIPTDIR/tooltip.sh t_d_tool01_right down &

# Education

# Games
[module/dosbox01]
inherit = module/launch_base

label = ${icons-launch.i_dosbox01}

click-left = $_SCRIPTDIR/event_launchbar.sh dosbox01_left &
click-right =$_SCRIPTDIR/event_launchbar.sh dosbox01_right &
scroll-up = $_SCRIPTDIR/tooltip.sh t_dosbox01_left up &
scroll-down = $_SCRIPTDIR/tooltip.sh t_dosbox01_right down &

# Graphics
[module/scan01]
inherit = module/launch_base

label = ${icons-launch.i_scan01}

click-left = $_SCRIPTDIR/event_launchbar.sh scan01_left &
click-right =$_SCRIPTDIR/event_launchbar.sh scan01_right &
scroll-up = $_SCRIPTDIR/tooltip.sh t_scan01_left up &
scroll-down = $_SCRIPTDIR/tooltip.sh t_scan01_right down &

[module/pic01]
inherit = module/launch_base

label = ${icons-launch.i_pic01}

click-left = $_SCRIPTDIR/event_launchbar.sh pic01_left &
click-right =$_SCRIPTDIR/event_launchbar.sh pic01_right &
scroll-up = $_SCRIPTDIR/tooltip.sh t_pic01_left up &
scroll-down = $_SCRIPTDIR/tooltip.sh t_pic01_right down &

# Internet
[module/web01]
inherit = module/launch_base

label = ${icons-launch.i_web01}

click-left = $_SCRIPTDIR/event_launchbar.sh web01_left &
click-right =$_SCRIPTDIR/event_launchbar.sh web01_right &
scroll-up = $_SCRIPTDIR/tooltip.sh t_web01_left up &
scroll-down = $_SCRIPTDIR/tooltip.sh t_web01_right down &

[module/mail01]
inherit = module/launch_base

label = ${icons-launch.i_mail01}

click-left = $_SCRIPTDIR/event_launchbar.sh mail01_left &
click-right =$_SCRIPTDIR/event_launchbar.sh mail01_right &
scroll-up = $_SCRIPTDIR/tooltip.sh t_mail01_left up &
scroll-down = $_SCRIPTDIR/tooltip.sh t_mail01_right down &

[module/download01]
inherit = module/launch_base

label = ${icons-launch.i_download01}

click-left = $_SCRIPTDIR/event_launchbar.sh download01_left &
click-right =$_SCRIPTDIR/event_launchbar.sh download01_right &
scroll-up = $_SCRIPTDIR/tooltip.sh t_download01_left up &
scroll-down = $_SCRIPTDIR/tooltip.sh t_download01_right down &

[module/messenger01]
inherit = module/launch_base

label = ${icons-launch.i_messenger01}

click-left = $_SCRIPTDIR/event_launchbar.sh messenger01_left &
click-right =$_SCRIPTDIR/event_launchbar.sh messenger01_right &
scroll-up = $_SCRIPTDIR/tooltip.sh t_messenger01_left up &
scroll-down = $_SCRIPTDIR/tooltip.sh t_messenger01_right down &

# Multimedia

# Office

[module/calendar01]
inherit = module/launch_base

label = ${icons-launch.i_calendar01}

click-left = $_SCRIPTDIR/event_launchbar.sh calendar01_left &
click-right =$_SCRIPTDIR/event_launchbar.sh calendar01_right &
scroll-up = $_SCRIPTDIR/tooltip.sh t_calendar01_left up &
scroll-down = $_SCRIPTDIR/tooltip.sh t_calendar01_right down &

[module/pdftool01]
inherit = module/launch_base

label = ${icons-launch.i_pdftool01}

click-left = $_SCRIPTDIR/event_launchbar.sh pdftool01_left &
click-right =$_SCRIPTDIR/event_launchbar.sh pdftool01_right &
scroll-up = $_SCRIPTDIR/tooltip.sh t_pdftool01_left up &
scroll-down = $_SCRIPTDIR/tooltip.sh t_pdftool01_right down &

[module/office01]
inherit = module/launch_base

label = ${icons-launch.i_office01}

click-left = $_SCRIPTDIR/event_launchbar.sh office01_left &
click-right =$_SCRIPTDIR/event_launchbar.sh office01_right &
scroll-up = $_SCRIPTDIR/tooltip.sh t_office01_left up &
scroll-down = $_SCRIPTDIR/tooltip.sh t_office01_right down &

[module/office02]
inherit = module/launch_base

label = ${icons-launch.i_office02}

click-left = $_SCRIPTDIR/event_launchbar.sh office02_left &
click-right =$_SCRIPTDIR/event_launchbar.sh office02_right &
scroll-up = $_SCRIPTDIR/tooltip.sh t_office02_left up &
scroll-down = $_SCRIPTDIR/tooltip.sh t_office02_right down &

[module/office03]
inherit = module/launch_base

label = ${icons-launch.i_office03}

click-left = $_SCRIPTDIR/event_launchbar.sh office03_left &
click-right =$_SCRIPTDIR/event_launchbar.sh office03_right &
scroll-up = $_SCRIPTDIR/tooltip.sh t_office03_left up &
scroll-down = $_SCRIPTDIR/tooltip.sh t_office03_right down &

[module/office04]
inherit = module/launch_base

label = ${icons-launch.i_office04}

click-left = $_SCRIPTDIR/event_launchbar.sh office04_left &
click-right =$_SCRIPTDIR/event_launchbar.sh office04_right &
scroll-up = $_SCRIPTDIR/tooltip.sh t_office04_left up &
scroll-down = $_SCRIPTDIR/tooltip.sh t_office04_right down &

# Other
[module/other01]
inherit = module/launch_base

label = ${icons-launch.i_other01}

click-left = $_SCRIPTDIR/event_launchbar.sh other01_left &
click-right =$_SCRIPTDIR/event_launchbar.sh other01_right &
scroll-up = $_SCRIPTDIR/tooltip.sh t_other01_left up &
scroll-down = $_SCRIPTDIR/tooltip.sh t_other01_right down &

# System

[module/fm01]
inherit = module/launch_base

label = ${icons-launch.i_fm01}

click-left = $_SCRIPTDIR/event_launchbar.sh fm01_left &
click-right =$_SCRIPTDIR/event_launchbar.sh fm01_right &
scroll-up = $_SCRIPTDIR/tooltip.sh t_fm01_left up &
scroll-down = $_SCRIPTDIR/tooltip.sh t_fm01_right down &

[module/fm02]
inherit = module/launch_base

label = ${icons-launch.i_fm02}

click-left = $_SCRIPTDIR/event_launchbar.sh fm02_left &
click-right =$_SCRIPTDIR/event_launchbar.sh fm02_right &
scroll-up = $_SCRIPTDIR/tooltip.sh t_fm02_left up &
scroll-down = $_SCRIPTDIR/tooltip.sh t_fm02_right down &

[module/fm03]
inherit = module/launch_base

label = ${icons-launch.i_fm03}

click-left = $_SCRIPTDIR/event_launchbar.sh fm03_left &
click-right =$_SCRIPTDIR/event_launchbar.sh fm03_right &
scroll-up = $_SCRIPTDIR/tooltip.sh t_fm03_left up &
scroll-down = $_SCRIPTDIR/tooltip.sh t_fm03_right down &

[module/fm04]
inherit = module/launch_base

label = ${icons-launch.i_fm04}

click-left = $_SCRIPTDIR/event_launchbar.sh fm04_left &
click-right =$_SCRIPTDIR/event_launchbar.sh fm04_right &
scroll-up = $_SCRIPTDIR/tooltip.sh t_fm04_left up &
scroll-down = $_SCRIPTDIR/tooltip.sh t_fm04_right down &

[module/terminal01]
inherit = module/launch_base

label = ${icons-launch.i_terminal01}

click-left = $_SCRIPTDIR/event_launchbar.sh terminal01_left &
click-right =$_SCRIPTDIR/event_launchbar.sh terminal01_right &
scroll-up = $_SCRIPTDIR/tooltip.sh t_terminal01_left up &
scroll-down = $_SCRIPTDIR/tooltip.sh t_terminal01_right down &

[module/terminal02]
inherit = module/launch_base

label = ${icons-launch.i_terminal02}

click-left = $_SCRIPTDIR/event_launchbar.sh terminal02_left &
click-right =$_SCRIPTDIR/event_launchbar.sh terminal02_right &
scroll-up = $_SCRIPTDIR/tooltip.sh t_terminal02_left up &
scroll-down = $_SCRIPTDIR/tooltip.sh t_terminal02_right down &

[module/package01]
inherit = module/launch_base

label = ${icons-launch.i_package01}

click-left = $_SCRIPTDIR/event_launchbar.sh package01_left &
click-right =$_SCRIPTDIR/event_launchbar.sh package01_right &
scroll-up = $_SCRIPTDIR/tooltip.sh t_package01_left up &
scroll-down = $_SCRIPTDIR/tooltip.sh t_package01_right down &

[module/package02]
inherit = module/launch_base

label = ${icons-launch.i_package02}

click-left = $_SCRIPTDIR/event_launchbar.sh package02_left &
click-right =$_SCRIPTDIR/event_launchbar.sh package02_right &
scroll-up = $_SCRIPTDIR/tooltip.sh t_package02_left up &
scroll-down = $_SCRIPTDIR/tooltip.sh t_package02_right down &

[module/emu01]
inherit = module/launch_base

label = ${icons-launch.i_emu01}

click-left = $_SCRIPTDIR/event_launchbar.sh emu01_left &
click-right =$_SCRIPTDIR/event_launchbar.sh emu01_right &
scroll-up = $_SCRIPTDIR/tooltip.sh t_emu01_left up &
scroll-down = $_SCRIPTDIR/tooltip.sh t_emu01_right down &

[module/emu02]
inherit = module/launch_base

label = ${icons-launch.i_emu02}

click-left = $_SCRIPTDIR/event_launchbar.sh emu02_left &
click-right =$_SCRIPTDIR/event_launchbar.sh emu02_right &
scroll-up = $_SCRIPTDIR/tooltip.sh t_emu02_left up &
scroll-down = $_SCRIPTDIR/tooltip.sh t_emu02_right down &

[module/hw01]
inherit = module/launch_base

label = ${icons-launch.i_hw01}

click-left = $_SCRIPTDIR/event_launchbar.sh hw01_left &
click-right =$_SCRIPTDIR/event_launchbar.sh hw01_right &
scroll-up = $_SCRIPTDIR/tooltip.sh t_hw01_left up &
scroll-down = $_SCRIPTDIR/tooltip.sh t_hw01_right down &

# Utility

[module/editor01]
inherit = module/launch_base

label = ${icons-launch.i_editor01}

click-left = $_SCRIPTDIR/event_launchbar.sh editor01_left &
click-right =$_SCRIPTDIR/event_launchbar.sh editor01_right &
scroll-up = $_SCRIPTDIR/tooltip.sh t_editor01_left up &
scroll-down = $_SCRIPTDIR/tooltip.sh t_editor01_right down &

[module/editor02]
inherit = module/launch_base

label = ${icons-launch.i_editor02}

click-left = $_SCRIPTDIR/event_launchbar.sh editor02_left &
click-right =$_SCRIPTDIR/event_launchbar.sh editor02_right &
scroll-up = $_SCRIPTDIR/tooltip.sh t_editor02_left up &
scroll-down = $_SCRIPTDIR/tooltip.sh t_editor02_right down &

[module/calculator01]
inherit = module/launch_base

label = ${icons-launch.i_calculator01}

click-left = $_SCRIPTDIR/event_launchbar.sh calculator01_left &
click-right =$_SCRIPTDIR/event_launchbar.sh calculator01_right &
scroll-up = $_SCRIPTDIR/tooltip.sh t_calculator01_left up &
scroll-down = $_SCRIPTDIR/tooltip.sh t_calculator01_right down &

[module/search01]
inherit = module/launch_base

label = ${icons-launch.i_search01}

click-left = $_SCRIPTDIR/event_launchbar.sh search01_left &
click-right =$_SCRIPTDIR/event_launchbar.sh search01_right &
scroll-up = $_SCRIPTDIR/tooltip.sh t_search01_left up &
scroll-down = $_SCRIPTDIR/tooltip.sh t_search01_right down &

[module/disk01]
inherit = module/launch_base

label = ${icons-launch.i_disk01}

click-left = $_SCRIPTDIR/event_launchbar.sh disk01_left &
click-right =$_SCRIPTDIR/event_launchbar.sh disk01_right &
scroll-up = $_SCRIPTDIR/tooltip.sh t_disk01_left up &
scroll-down = $_SCRIPTDIR/tooltip.sh t_disk01_right down &

# Special User Apps
# Fully freely configurable modules

[module/user01]
inherit = module/launch_base

label = ${icons-launch.i_user01}

click-left = $_SCRIPTDIR/event_launchbar.sh user01_left &
click-right =$_SCRIPTDIR/event_launchbar.sh user01_right &
scroll-up = $_SCRIPTDIR/tooltip.sh t_user01_left up &
scroll-down = $_SCRIPTDIR/tooltip.sh t_user01_right down &

[module/user02]
inherit = module/launch_base

label = ${icons-launch.i_user02}

click-left = $_SCRIPTDIR/event_launchbar.sh user02_left &
click-right =$_SCRIPTDIR/event_launchbar.sh user02_right &
scroll-up = $_SCRIPTDIR/tooltip.sh t_user02_left up &
scroll-down = $_SCRIPTDIR/tooltip.sh t_user02_right down &

[module/user03]
inherit = module/launch_base

label = ${icons-launch.i_user03}

click-left = $_SCRIPTDIR/event_launchbar.sh user03_left &
click-right =$_SCRIPTDIR/event_launchbar.sh user03_right &
scroll-up = $_SCRIPTDIR/tooltip.sh t_user03_left up &
scroll-down = $_SCRIPTDIR/tooltip.sh t_user03_right down &

[module/user04]
inherit = module/launch_base

label = ${icons-launch.i_user04}

click-left = $_SCRIPTDIR/event_launchbar.sh user04_left &
click-right =$_SCRIPTDIR/event_launchbar.sh user04_right &
scroll-up = $_SCRIPTDIR/tooltip.sh t_user04_left up &
scroll-down = $_SCRIPTDIR/tooltip.sh t_user04_right down &

[module/user05]
inherit = module/launch_base

label = ${icons-launch.i_user05}

click-left = $_SCRIPTDIR/event_launchbar.sh user05_left &
click-right =$_SCRIPTDIR/event_launchbar.sh user05_right &
scroll-up = $_SCRIPTDIR/tooltip.sh t_user05_left up &
scroll-down = $_SCRIPTDIR/tooltip.sh t_user05_right down &


# free configurable user space

[module/user_space01]
inherit = module/launchbar_spacebase

format-padding = ${app-launch.user_space01_padding}

[module/user_space02]
inherit = module/launchbar_spacebase

format-padding = ${app-launch.user_space02_padding}

[module/user_space03]
inherit = module/launchbar_spacebase

format-padding = ${app-launch.user_space03_padding}
