# launchbar workspace modules config
# accessing workspaces and files
# use in launchbar_left, launchbar_center or launchbar_right 

######################################

# workspaces as defined in i3 config
# each module can access two workspaces

[module/launch_i3_ws_01]
inherit = module/launch_base

label = ${icons-ws.i_ws_01}
format-foreground = ${colors.secondary}

click-left = $_i3_SCRIPTDIR/i3_open_ws.sh 1 s_ws1
click-right = $_i3_SCRIPTDIR/i3_open_ws.sh 10 s_ws10
scroll-up = $_SCRIPTDIR/tooltip.sh t_ws_1 up &
scroll-down = $_SCRIPTDIR/tooltip.sh t_ws_10 down &

[module/launch_i3_ws02]
inherit = module/launch_base

label = ${icons-ws.i_ws_02}
format-foreground = ${colors.secondary}

click-left = $_i3_SCRIPTDIR/i3_open_ws.sh 2 s_ws2
click-right = $_i3_SCRIPTDIR/i3_open_ws.sh 3 s_ws3
scroll-up = $_SCRIPTDIR/tooltip.sh t_ws_2 up &
scroll-down = $_SCRIPTDIR/tooltip.sh t_ws_3 down &

[module/launch_i3_ws04]
inherit = module/launch_base

label = ${icons-ws.i_ws_04}
format-foreground = ${colors.secondary}

click-left = $_i3_SCRIPTDIR/i3_open_ws.sh 4 s_ws4
click-right = $_i3_SCRIPTDIR/i3_open_ws.sh 5 s_ws5
scroll-up = $_SCRIPTDIR/tooltip.sh t_ws_4 up &
scroll-down = $_SCRIPTDIR/tooltip.sh t_ws_5 down &

[module/launch_i3_ws06]
inherit = module/launch_base

label = ${icons-ws.i_ws_06}
format-foreground = ${colors.secondary}

click-left = $_i3_SCRIPTDIR/i3_open_ws.sh 6 s_ws6
click-right = $_i3_SCRIPTDIR/i3_open_ws.sh 7 s_ws7
scroll-up = $_SCRIPTDIR/tooltip.sh t_ws_6 up &
scroll-down = $_SCRIPTDIR/tooltip.sh t_ws_7 down &

[module/launch_i3_ws08]
inherit = module/launch_base

label = ${icons-ws.i_ws_08}
format-foreground = ${colors.secondary}

click-left = $_i3_SCRIPTDIR/i3_open_ws.sh 8 s_ws8
click-right = $_i3_SCRIPTDIR/i3_open_ws.sh 9 s_ws9
scroll-up = $_SCRIPTDIR/tooltip.sh t_ws_8 up &
scroll-down = $_SCRIPTDIR/tooltip.sh t_ws_9 down &

# file openers

[module/launch_file_01]
inherit = module/launch_base

label = ${icons-files.i_file01}
format-foreground = ${colors.tertiary}

click-left = $_i3_SCRIPTDIR/i3_open_file.sh file01
click-right = $_i3_SCRIPTDIR/i3_open_file.sh file01_alt
scroll-up = $_SCRIPTDIR/tooltip.sh t_file01 up &
scroll-down = $_SCRIPTDIR/tooltip.sh t_file01_alt down &

[module/launch_file_02]
inherit = module/launch_base

label = ${icons-files.i_file02}
format-foreground = ${colors.tertiary}

click-left = $_i3_SCRIPTDIR/i3_open_file.sh file02
click-right = $_i3_SCRIPTDIR/i3_open_file.sh file02_alt
scroll-up = $_SCRIPTDIR/tooltip.sh t_file02 up &
scroll-down = $_SCRIPTDIR/tooltip.sh t_file02_alt down &

[module/launch_file_03]
inherit = module/launch_base

label = ${icons-files.i_file03}
format-foreground = ${colors.tertiary}

click-left = $_i3_SCRIPTDIR/i3_open_file.sh file03
click-right = $_i3_SCRIPTDIR/i3_open_file.sh file03_alt
scroll-up = $_SCRIPTDIR/tooltip.sh t_file03 up &
scroll-down = $_SCRIPTDIR/tooltip.sh t_file03_alt down &

[module/launch_file_04]
inherit = module/launch_base

label = ${icons-files.i_file04}
format-foreground = ${colors.tertiary}

click-left = $_i3_SCRIPTDIR/i3_open_file.sh file04
click-right = $_i3_SCRIPTDIR/i3_open_file.sh file04_alt
scroll-up = $_SCRIPTDIR/tooltip.sh t_file04 up &
scroll-down = $_SCRIPTDIR/tooltip.sh t_file04_alt down &

[module/launch_file_05]
inherit = module/launch_base

label = ${icons-files.i_file05}
format-foreground = ${colors.tertiary}

click-left = $_i3_SCRIPTDIR/i3_open_file.sh file05
click-right = $_i3_SCRIPTDIR/i3_open_file.sh file05_alt
scroll-up = $_SCRIPTDIR/tooltip.sh t_file05 up &
scroll-down = $_SCRIPTDIR/tooltip.sh t_file05_alt down &

