# modules for bar main

#needs polybar version 3.7.1
[module/screenshot]
type = custom/text

label = ""
format = %{A1: :}%{A3: :} <label>  %{A}%{A}
#format = %{A1:$_SCRIPTDIR/info_screenshot.sh left:}%{A3: :} <label>  %{A}%{A}

format-prefix = %{A1:$_SCRIPTDIR/event_screenshot.sh left:}%{A6:$_SCRIPTDIR/event_screenshot.sh dbl_left:}%{A3:$_SCRIPTDIR/event_screenshot.sh right:}%{A8:$_SCRIPTDIR/event_screenshot.sh dbl_right:}%{A4:$_SCRIPTDIR/event_screenshot.sh up:}%{A5:$_SCRIPTDIR/event_screenshot.sh down:}%{A}%{A}%{A}%{A}%{A}%{A}
;format-prefix = %{A1:$_SCRIPTDIR/event_screenshot.sh left:}%{A3:$_SCRIPTDIR/event_screenshot.sh right:}%{A}%{A}
format-prefix-foreground = ${colors.primary}

scroll-up = " "
scroll-down = " "

[module/display]
type = custom/script

exec = echo " $(xrandr | grep " connected" | awk '{print $1}')"

label = %output%
format = " <label>  "

click-left = "$_SCRIPTDIR/info_display.sh left"
click-right = "$_SCRIPTDIR/info_display.sh right"
double-click-left = "$_SCRIPTDIR/info_display.sh dbl_left"
scroll-up = " "
scroll-down = " "

;format-prefix = %{A1:$_SCRIPTDIR/event_display.sh left:}%{A3:$_SCRIPTDIR/event_display.sh right:}%{A4: :}%{A5: :}󰍺%{A}%{A}%{A}%{A}
format-prefix = %{A1:$_SCRIPTDIR/event_display.sh left:}%{A6:$_SCRIPTDIR/event_display.sh dbl_left:}%{A3:$_SCRIPTDIR/event_display.sh right:}%{A8:$_SCRIPTDIR/event_display.sh dbl_right:}%{A4:$_SCRIPTDIR/event_display.sh up:}%{A5:$_SCRIPTDIR/event_display.sh down:}󰍺%{A}%{A}%{A}%{A}%{A}%{A}
format-prefix-foreground = ${colors.primary}

